import type { Metadata } from "next";
import { IBM_Plex_Sans, Pixelify_Sans, Sixtyfour, JetBrains_Mono, Press_Start_2P } from "next/font/google";
import { ThemeProvider } from "next-themes";
import ThemeWrapper from "@/components/providers/ThemeWrapper";
import "./globals.css";
import "./retro-globals.css";

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans",
});
const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-pixelify-sans",
});
const sixtyfour = Sixtyfour({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sixtyfour",
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrains-mono",
});

const pressStart2p = Press_Start_2P({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-press-start-2p",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmPlexSans.variable} ${pixelifySans.variable} ${sixtyfour.variable} ${jetBrainsMono.variable} ${pressStart2p.variable} antialiased`}>
        <ThemeProvider
        attribute="class"
        defaultTheme="default"
        themes={[
          "default",
          "sega",
          "nintendo",
          "gameboy",
          "atari",
          "arcade",
          "neo-geo",
          "soft-pop",
          "vhs",
          "pacman",
          "cassette",
          "rusty-byte",
        ]}
        enableSystem={false}
        enableColorScheme={false}
      >
          <ThemeWrapper>{children}</ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
